# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - azure-vote/*
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        dockerfile: $(Build.SourcesDirectory)/azure-vote/Dockerfile
        containerRegistry: ACR
        repository: azure-vote-front
        tags: |
          $(tag)
#    - task: PublishBuildArtifacts@1
#      inputs:
#        PathtoPublish: '$(Build.SourcesDirectory)/vote'
#        ArtifactName: 'helm'
#        publishLocation: 'Container'
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
    - task: HelmDeploy@0
      inputs:
        command: 'package'
        chartPath: 'vote'
        chartVersion: '$(Build.BuildId)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'helm'
        publishLocation: 'Container'
    
    