Namespace:
  name: dev
Deployment:
  enabled: true
container:
  replicas: 1
  image: doug2901/pywebapp:1.0
  resources:
    request: 
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m
  port: 5000


services:
  enabled: true
  port: 80
  targetPort: 5000
  nodePort: 30000
  type: LoadBalancer
hpa:
  enabled: false
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

#helm install --debug --dry-run meusite ./meuchart