{{ if eq .Values.Deployment.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.Namespace.name }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- with .Values.container }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
  template:
    metadata:
      name: {{ $.Release.Name }}
      labels:
        app: {{ $.Release.Name }}
    spec:
      containers:
      - name: {{ $.Release.Name }}
        image: unyleyaacr.azurecr.io/azure-vote-front:{{ .tag }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: REDIS
          value: "azure-vote-back"
        ports:
        - containerPort: {{ .port }}
          name: redis
  {{- end }}
{{- end }}        
